### ISSUE TITLE
Quit key binding CTRL+Q freeze session

### ISSUE THREAD

**Issue by fflaten** [ironmansoftware/psedit#12]
Closing using File -> Quit works, but using the CTRL+Q shortcut freezes the session.
Tested with Windows PS 5.1 and PS 7.3 using Windows Terminal and Conhost.

**Comment by halvarsson** [comment]
I believe this was fixed in #3

**Comment by fflaten** [comment]
Oh my bad, forgot to check the unreleased commits. 🤦‍♂️

I see there's a fix for positional `-Path` too. 👏

**Comment by adamdriscoll** [comment]
Closing since this is fixed! I'll push a new version tomorrow to the gallery since we have some cool stuff in there already.
