### ISSUE TITLE
Opening 'Help > Docs' quits PSEdit and leaves mouse tracking on (showing characters in the terminal when mouse moves)

### ISSUE THREAD

**Issue by Jawz84** [ironmansoftware/psedit#2]
## How to reproduce
- go to shell.azure.com
- open Bash cloudshell
- start pwsh
- install-module psedit -force
- `show-pseditor` 
- go to menu Help > Docs

## Expected
When clicking Help > Docs, the program takes me to the docs. 

## Actual
The program exits, without clearing the buffer, and mouse tracking mode is still on:
![image](https://user-images.githubusercontent.com/26464885/203932963-d548c3fd-0371-4075-b335-bf90eed4c69c.png)

## Remarks
Thanks for building this fun ascii based editor :)

**Comment by Jawz84** [comment]
Relevant lines of code are here: https://github.com/ironmansoftware/psedit/blob/f103aa16587c189cad3342ebe96441b878c1d559/ShowEditorCommand.cs#L130

Azure cloud shell probably does not permit starting new process that way?

**Comment by adamdriscoll** [comment]
@Jawz84 - Yeah. That's probably the exact problem.

**Comment by SteveL-MSFT** [comment]
Perhaps wrap in `try...catch` and if fails emit a message that it's not supported in that environment?

**Comment by adamdriscoll** [comment]
That makes sense. Maybe emit the docs URL.

**Comment by adamdriscoll** [comment]
I'm also open to just having this forward to this repo's readme rather than docs.poshtools.com since it's no longer part of that suite.

**Comment by En3Tho** [comment]
I've found a long time ago that it's better to have this in `finally` block of command/app:
```fsharp
finally
        if not Console.IsInputRedirected then
            Console.Write("\u001b[?1h\u001b[?1003l")
```
It's in F# but you get the idea. This disables mouse tracking. I first stumbled upon this bug using Out-ConsoleGridView which uses Gui.cs too. I've been using this command to disable mouse tracking in my pwsh apps too. Works nice across on windows/linux

**Comment by halvarsson** [comment]
I have added the fix for mouse tracking staying on, and confirmed that it solves the described issue in Cloud shell. 
  
I also replaced the Process start with just a MessageBox, linking to Github. This gets rid of this issue entirely, but incase something else crashes then at least the mouse tracking wont stay messed up :)

![image](https://github.com/ironmansoftware/psedit/assets/18571127/f2f79872-0bcb-44e6-ba0e-6804323f2538)
