### ISSUE TITLE
Update Edit Menu

### ISSUE THREAD

**Issue by jdhitsolutions** [ironmansoftware/psedit#23]
I was about to ask if you were going to add support for cut, copy, and paste, then I tried the usual keyboard shortcuts and they worked. I suggest adding Cut, Copy, and Paste items to the Edit menu.

**Comment by halvarsson** [comment]
We actually already support it, but on right-click :)

![image](https://user-images.githubusercontent.com/18571127/220763815-729e9dec-8d9a-4b22-9736-7da5a7c2e9dd.png)

**Comment by jdhitsolutions** [comment]
I don't know why I never thought to try that.

**Comment by adamdriscoll** [comment]
Closing this as completed. We could update the readme to include this info...
