### ISSUE TITLE
status bar is always reflecting 1 redraw behind

### ISSUE THREAD

**Issue by halvarsson** [ironmansoftware/psedit#33]
I noticed this while working with the data in the status bar, it seems like when we move the cursor, the CursorPosition that we catch for Status bar in UpdatePosition is the position before the update.. So it sets the status bar to the previous position you were at and then calls the Redraw() on the texteditor, from which now the Cursor Position is accurate

See below where I have the cursor on column 2, but it reflects it as 1

![image](https://user-images.githubusercontent.com/18571127/221701232-ec5186dc-d8ae-4b17-a269-3dde1c820990.png)

And when I move the cursor, it ends up being 2
![image](https://user-images.githubusercontent.com/18571127/221701853-02db0f93-1148-45f3-b57d-bc7ed9e5f6e9.png)

**Comment by adamdriscoll** [comment]
@halvarsson Let me know if you want me to add you as a maintainer to this project! I can hardly keep up with reviewing your changes :)

**Comment by halvarsson** [comment]
@adamdriscoll 
Sure I would be happy to help as a maintainer on the project! :) 

I will keep going over the current functionality and get it 100% working, as there's been some quirks with it, and then I will start getting new features added :)
