### ISSUE TITLE
Ignore errors on non-PowerShell files

### ISSUE THREAD

**Issue by jdhitsolutions** [ironmansoftware/psedit#34]
If I understand correctly, PSEdit is analyzing PowerShell script files for errors. But it shouldn't assume that every file is a PowerShell file. I have a JSON file open in the editor, and I shouldn't get errors. 
![image](https://user-images.githubusercontent.com/12089920/221910206-b4a5b9de-73ce-46cc-8cca-94c753df2752.png)

This can be misleading for less experienced users.

**Comment by halvarsson** [comment]
Currently the editor is always assuming the content to be Powershell, I think we need to split the logic out and make a base TextEditor which can edit text, and then some easy way to add syntax highlighting, autocomplete etc. ontop of this based on the filetype you are working on... Would be really neat if we supported XML, JSON etc :-)
