### ISSUE TITLE
Open directory list in current location

### ISSUE THREAD

**Issue by jdhitsolutions** [ironmansoftware/psedit#35]
It would be helpful if the open file dialog box could default to the current location.

**Comment by jdhitsolutions** [comment]
Thanks @halvarsson for handling these issues. I wish I had the skill set to contribute to the code. The best I can do is usability testing and feedback.

**Comment by halvarsson** [comment]
No problem! Thank you also for creating these issues so we can improve the experience, I think every detail matters :-)
