### ISSUE TITLE
Feature request: Indicate unsaved file

### ISSUE THREAD

**Issue by jdhitsolutions** [ironmansoftware/psedit#46]
It would be very helpful if there was a visual indication that a file has unsaved changes. You could use the same indicator to prompt to save on quitting.

**Comment by halvarsson** [comment]
This is currently indicated by the * next to the filename whenever you edit a file :-) 

It is a bit unreliable as its not matching on the exact content like the prompt on quitting, and it's 1 redraw behind sometimes so you might need to write multiple characters for it to reflect, but it should clear the star when you save etc.

![image](https://user-images.githubusercontent.com/18571127/228951480-de0cb145-39b2-4eb3-87ee-2e8b4dcee00f.png)

**Comment by jdhitsolutions** [comment]
I was looking for something like that. I don't get the same result. This file has several changes and is unsaved.

![image](https://user-images.githubusercontent.com/12089920/228969709-757036cf-86d8-4e9e-9c21-acadeaea5413.png)

**Comment by jdhitsolutions** [comment]
Running in Windows Terminal in PowerShell 7.3.3 if that makes a difference.

**Comment by halvarsson** [comment]
Is this on the latest build? 

I submitted the PR #31 previously which fixed the old behavior where the star would only show up when you had an Unsaved file which you then saved (and it would put *)

Note that the updated version is currently not published on PSGallery

**Comment by jdhitsolutions** [comment]
Then no. I only have the version published in the PSGallery.

**Comment by halvarsson** [comment]
Ah, yep thats probably the issue you are running into then, I committed the fix hours after 0.0.6 was released, so it should be included when we eventually release 0.0.7 :-) I am working on polishing the existing features and adding a few new ones currently and I will request a new build soon

I will close the issue for now
