### ISSUE TITLE
Most pop-up windows hide the cursor, then do not make it visible again.

### ISSUE THREAD

**Issue by mklement0** [ironmansoftware/psedit#51]
E.g., View > Errors hides the cursor, but then doesn't make it visible again on dismissing the pop-up window.

View > Syntax Errors seems to be the only exception, which not only makes a mistakenly hidden cursor visible again, but also shows it inside the pop-up window.

**Comment by halvarsson** [comment]
This was due to an issue in Terminal.Gui, https://github.com/gui-cs/Terminal.Gui/issues/2326

I have upgraded to 1.10.0 which contains a fix, so the cursor should now always remain visible

**Comment by mklement0** [comment]
🙏
