### ISSUE TITLE
Consider prompting for saving before quitting when the buffer has been modified.

### ISSUE THREAD

**Issue by mklement0** [ironmansoftware/psedit#52]
Currently, <kbd>Ctrl+Q</kbd> quits _unconditionally_, quietly discarding any unsaved changes, which is unexpected.

Please consider presenting a modal dialog that prompts for saving first (yes/no/cancel), if needed,
and possibly also offering a dedicated save-then-quit command.

**Comment by halvarsson** [comment]
Hi

We added a prompt on quitting a while back but this is not in the PSGallery version yet, I did however spot that the CTRL+Q functionality isn't working properly in Windows Terminal when defined in the MenuBar. I added it as a keyboard shortcut in the StatusBar as well, and now it works consistently (this weird behavior is reproducable in Terminal.Gui too)

![ctrl-q-func](https://github.com/ironmansoftware/psedit/assets/18571127/c7e34aad-41a6-40a1-a84a-3585da4da489)

There is alot of improvements to psedit thats already in the repo, if you wish to clone and check it out :)

**Comment by mklement0** [comment]
Thank you, @halvarsson, both for the info and your PRs.
