### ISSUE TITLE
Suggestion: make Enter an alternative keypress to Tab when selecting a completion from a pop-up list

### ISSUE THREAD

**Issue by mklement0** [ironmansoftware/psedit#59]
When multiple completions are found, using up/down-arrow followed by <kbd>Enter</kbd> to select the highlighted completion doesn't work and simply inserts a newline - currently, only <kbd>Tab</kbd> works.

Given that both PSReadLine and Visual Studio Code (only / also) accept <kbd>Enter</kbd> in this situation, it would be nice to allow the latter in `Show-PSEditor` too.

**Comment by halvarsson** [comment]
Unfortunately the Autocomplete selection is mapped to a single key

I agree that Enter would be a better behavior, cause this is a dropdown menu, similar to VSCode etc, and the behavior there is always Enter. I think TAB makes sense when there's no menu selection in the terminal, but we got a dropdown with selection being selectable with up/down etc, so I have switched it to Enter

**Comment by mklement0** [comment]
Great, thank you.
